/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
static yyconst short int yy_acclist[190] =
    {   0,
       51,   49,   50,   45,   49,   50,   45,   50,   49,   50,
       49,   50,   25,   49,   50,   34,   49,   50,   35,   49,
       50,   23,   49,   50,   21,   49,   50,   37,   49,   50,
       22,   49,   50,   41,   49,   50,   24,   49,   50,   42,
       49,   50,   39,   49,   50,   36,   49,   50,   29,   49,
       50,   16,   49,   50,   28,   49,   50,   46,   49,   50,
       32,   49,   50,   33,   49,   50,   46,   49,   50,   46,
       49,   50,   46,   49,   50,   46,   49,   50,   46,   49,
       50,   46,   49,   50,   46,   49,   50,   46,   49,   50,
       46,   49,   50,   46,   49,   50,   46,   49,   50,   46,

       49,   50,   30,   49,   50,   31,   49,   50,   18,   44,
       19,   20,   40,   43,   48,   47,   42,   38,   26,   17,
       27,   46,   46,   46,   46,   46,   46,   46,   46,    1,
       46,   46,   46,   46,   11,   46,   46,   46,   46,   47,
        9,   46,   46,   46,   46,   46,    4,   46,   46,   46,
       15,   46,   10,   46,   46,   46,   46,   46,   46,    2,
       46,   46,   46,   46,   46,   13,   46,   46,    7,   46,
       46,   14,   46,   46,   12,   46,   46,    3,   46,   46,
       46,    6,   46,   46,   46,    8,   46,    5,   46
    } ;

static yyconst short int yy_accept[112] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   13,   16,
       19,   22,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  103,  106,
      109,  110,  110,  111,  111,  112,  113,  114,  115,  116,
      117,  117,  118,  119,  120,  121,  122,  123,  124,  125,
      126,  127,  128,  129,  130,  132,  133,  134,  135,  137,
      138,  139,  140,  141,  143,  144,  145,  146,  147,  149,
      150,  151,  153,  155,  156,  157,  158,  159,  160,  162,
      163,  164,  165,  166,  168,  169,  171,  172,  174,  175,

      177,  178,  180,  181,  182,  184,  185,  186,  188,  190,
      190
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,    1,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       22,   23,   24,    1,   25,    1,   26,   27,   28,   29,

       30,   31,   21,   32,   33,   21,   34,   35,   21,   36,
       37,   21,   21,   38,   39,   40,   41,   21,   42,   21,
       21,   21,   43,    1,   44,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1
    } ;

static yyconst short int yy_base[114] =
    {   0,
        0,    0,  127,  128,  128,  128,  107,   40,  128,  128,
      128,  128,  115,  128,  112,   33,   38,   36,  107,  128,
      103,  102,  101,    0,  128,  128,   83,   80,   80,   81,
       24,   84,   77,   20,   75,   82,   73,   78,  128,  128,
      128,   49,  128,   50,  128,  128,  128,   94,  128,    0,
       93,   43,  128,  128,  128,  128,    0,   78,   76,   69,
       65,   68,   64,   65,    0,   72,   64,   58,    0,   57,
       54,   56,    0,    0,   62,   47,   55,   45,    0,   55,
       56,    0,    0,   40,   50,   44,   44,   44,    0,   46,
       35,   39,   33,    0,   40,    0,   33,    0,   35,    0,

       31,    0,   25,   27,    0,   32,   24,    0,    0,  128,
       90,   56,   93
    } ;

static yyconst short int yy_def[114] =
    {   0,
      110,    1,  110,  110,  110,  110,  110,  111,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  112,  110,  110,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  110,  110,
      110,  111,  110,  110,  110,  110,  110,  110,  110,  113,
      110,  110,  110,  110,  110,  110,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  113,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,

      112,  112,  112,  112,  112,  112,  112,  112,  112,    0,
      110,  110,  110
    } ;

static yyconst short int yy_nxt[173] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,    4,   26,    4,   27,   28,   29,   24,   30,
       31,   24,   32,   24,   33,   34,   35,   36,   24,   37,
       24,   38,   39,   40,   43,   47,   49,   48,   51,   62,
       52,   50,   67,   43,   42,   51,   68,   52,   57,  109,
       63,  108,   44,  107,   64,  106,  105,  104,  103,  102,
      101,   44,   42,  100,   99,   98,   97,   96,   95,   94,
       93,   92,   91,   90,   89,   42,   88,   87,   86,   42,
       42,   42,   42,   73,   85,   73,   84,   83,   82,   81,

       80,   79,   78,   77,   76,   75,   74,   48,   48,   72,
       71,   70,   69,   66,   65,   61,   60,   59,   58,   56,
       55,   54,   53,   46,   45,   41,  110,    3,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110
    } ;

static yyconst short int yy_chk[173] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   16,   17,   16,   18,   31,
       18,   17,   34,   42,   44,   52,   34,   52,  112,  107,
       31,  106,    8,  104,   31,  103,  101,   99,   97,   95,
       93,   42,   44,   92,   91,   90,   88,   87,   86,   85,
       84,   81,   80,   78,   77,   44,   76,   75,   72,   44,
      111,  111,  111,  113,   71,  113,   70,   68,   67,   66,

       64,   63,   62,   61,   60,   59,   58,   51,   48,   38,
       37,   36,   35,   33,   32,   30,   29,   28,   27,   23,
       22,   21,   19,   15,   13,    7,    3,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
#line 2 "scanner.l"
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<assert.h>

#define YY_DECL int alpha_yylex (void* yylval)

int token_counter = 0;

typedef enum {
    IF_T, ELSE_T, WHILE_T, FOR_T, FUNCTION_T, RETURN_T, BREAK_T, 
    CONTINUE_T, AND_T, NOT_T, OR_T, LOCAL_T, TRUE_T, FALSE_T, NIL_T,
    
    EQUAL_T, PLUS_T, MINUS_T, MUL_T, DIV_T, MOD_T, EQUAL_EQUAL_T, NOT_EQUAL_T, PLUS_PLUS_T, 
    MINUS_MINUS_T, GREATER_T, GREATER_EQUAL_T, LESS_T, LESS_EQUAL_T,
    
    CURLY_O_T, CURLY_C_T, SQUARE_BRACKET_O_T, SQUARE_BRACKET_C_T, DOT_T, DOT_DOT_T,
    PARENTHESIS_O_T, PARENTHESIS_C_T, SEMICOLON_T, COMMA_T, COLON_T, COLON_COLON_T,
    
    LINE_COMMENT_T, BLOCK_COMMENT_T,

    CONST_INT_T, CONST_REAL_T, STRING_T,

    ID_T, UNKNOWN_T, BEGINSTATE_FIRST_NODE
}TypeToken_t;

typedef struct alpha_token {
    unsigned int    numline;
    unsigned int    numToken;
    char            *content;
    
    TypeToken_t     type;

    char           *category;

    struct alpha_token *next;
} alpha_token_t;


char* isolate_string();
alpha_token_t* insert_new_token(alpha_token_t **lastNode, TypeToken_t type);
char *mystrcpy(char *str);
char* token_category(TypeToken_t token);
char* token2str(alpha_token_t *token);

#line 519 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 61 "scanner.l"


#line 673 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 111 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 128 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 63 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, IF_T);         }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, ELSE_T);       }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, WHILE_T);          }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, FOR_T);              }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, FUNCTION_T);   }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, RETURN_T);     }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, BREAK_T);      }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, CONTINUE_T);   }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, AND_T);        }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, NOT_T);        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, OR_T);         }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, LOCAL_T);     }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, TRUE_T);       }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, FALSE_T);      }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, NIL_T);        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 79 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, EQUAL_T);                  }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 80 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, EQUAL_EQUAL_T);      } 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 81 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, NOT_EQUAL_T);          }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 82 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, PLUS_PLUS_T);          }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 83 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, MINUS_MINUS_T);      }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 84 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, PLUS_T);                    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 85 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, MINUS_T);                  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 86 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, MUL_T);                      }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 87 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, DIV_T);                      }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 88 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, MOD_T);                      }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 89 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, LESS_EQUAL_T);        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 90 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, GREATER_EQUAL_T);  }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 91 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, GREATER_T);              }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 92 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, LESS_T);                    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 96 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, CURLY_O_T);      }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 97 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, CURLY_C_T);      }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 98 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, SQUARE_BRACKET_O_T);      }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 99 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, SQUARE_BRACKET_C_T);      }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 100 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, PARENTHESIS_O_T);      }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 101 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, PARENTHESIS_C_T);      }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 102 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, SEMICOLON_T);      }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 103 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, COMMA_T);      }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 104 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, COLON_COLON_T);     }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 105 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, COLON_T);      }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 106 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, DOT_DOT_T);     }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 107 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, DOT_T);      }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 111 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, CONST_INT_T);                    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 112 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, CONST_REAL_T);                   }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 113 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, STRING_T);                       }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 114 "scanner.l"
{                                                                                            }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 116 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, ID_T);             }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 118 "scanner.l"
{ insert_new_token( (alpha_token_t**) &yylval, LINE_COMMENT_T);    }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 120 "scanner.l"
{
    int openNestedCommentsBl = 1;
    int c;
    int firstLineComment = yylineno;
    int endLineComment = -1;
    
    printf("Begin a multi comment yytext: %s, in line: %d\n", yytext, firstLineComment);

    while( (c = input()) != EOF) {
        if(c == '*') {
            if( (c = input()) == '/') {
                --openNestedCommentsBl;
                if(openNestedCommentsBl != 0) {
                    printf("\tEnd nested multi comment in line: %d\n", yylineno);
                }
            }
            else {
                unput(c);
            }
        }
        else if(c == '/') {
            if( (c = input()) == '*') {
                ++openNestedCommentsBl;
                printf("\tBegin Nested multi comment yytext: %s, in line: %d\n", yytext, yylineno);
            }
            else {
                unput(c);
            }
        }
        if(openNestedCommentsBl == 0) break;
    }
    if(c == EOF) {
        printf("Unclosed multi-line comment. EXIT!\n");
        exit(1);
    } else {
        endLineComment = yylineno;
        printf("End block comment yylineno = %d\n", endLineComment);
    }
    insert_new_token( (alpha_token_t**) &yylval, BLOCK_COMMENT_T);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 161 "scanner.l"
{
    if(yytext[0] =='\"') {
        printf("Unclosed string in line: %d, yytext: %s\n", yylineno, yytext);
    } else {
        printf("Unexpected character: %s in line: %d\n", yytext, yylineno);
    }
    exit(1);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 170 "scanner.l"
ECHO;
	YY_BREAK
#line 1060 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 111 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 111 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 110);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 170 "scanner.l"



int main(int argc, char **argv) {
    alpha_token_t *headList = NULL;
    alpha_token_t *endList = NULL;
    alpha_token_t *traceList = NULL;

    FILE* fOutput;

    char cEndProgram = 'a';

    if(argc > 1) {
        if(!(yyin = fopen(argv[1], "r"))) {
            fprintf(stderr, "Error opening input file %s!\n", argv[1]);
            return 1;
        }
        if(argc == 3) {
            /* STDOUT -> FILE* */
            if(! (fOutput = fopen(argv[2], "w")) ) {
                fprintf(stderr, "Error opening output file %s!\n", argv[2]);
                return 1;
            }
        } else if (argc > 3) {
            fprintf(stderr, "Too arguments.\n");
            return 1;
        }
    }
    else {
        yyin = stdin;
    }

    headList = insert_new_token(&endList, BEGINSTATE_FIRST_NODE);
    
    alpha_yylex(endList);

    headList = headList->next; /* I don't to free the previous head Node. */

    traceList = headList;
    while(traceList != NULL)
    {
        if(argc == 3) {
            fprintf(fOutput, "%-5d: #%-10d \"%s\" %-15s %-10s %-15s %-10s\n",
                traceList->numline, \
                traceList->numToken, \
                traceList->content,   \
                " ",                     \
                traceList->category,         \
                " ",                            \
                token2str(traceList)         \
            );
        } else {
            printf("%-5d: #%-10d \"%s\" %-15s %-10s %-15s %-10s\n",
                traceList->numline, \
                traceList->numToken, \
                traceList->content,   \
                " ",                     \
                traceList->category,         \
                " ",                            \
                token2str(traceList)         \
            );
        }
        
        traceList = traceList->next;
    }

    while(cEndProgram != 'q') {
        printf("Type 'q' to end programm.\n");
        cEndProgram = getchar();
    }

    return 0;
}

char* isolate_string()
{
    int i = 0;
    char* c = (char*) malloc(  (1 + strlen(yytext)) * sizeof(char));

    int fullTheString = 0;

    if(c == NULL) return NULL;
    if(strlen(yytext) == 0) {
        c[0] = '\0';
        return c;
    }  

    while(yytext[i] != '\0')
    {
        if(i == 0) {
            /* Ignore the first quote character: ` " ` */
        } else {
            if(yytext[i] == '\\') {
                if(yytext[i+1] == 'n') {
                    c[fullTheString] = '\n';
                }
                else if(yytext[i+1] == 't') {
                    c[fullTheString] = '\t';
                }
                else if(yytext[i+1] == '\\') {
                    c[fullTheString] = '\\';
                } 
                else if(yytext[i+1] == '\"') {
                    c[fullTheString] = '\"';
                }
                else {
                    fprintf(stderr, "There is no case...\n");
                    exit(1);
                }
                ++i;
            } else {
                if(yytext[i] == '\"') {
                    break; /* The last quote character: ` " ` */
                }
                c[fullTheString] = yytext[i];
            }
            ++fullTheString;
        }
        ++i;
    }
    c[fullTheString] = '\0';

    return c;
}

alpha_token_t* insert_new_token(alpha_token_t **lastNode, TypeToken_t type)
{
    alpha_token_t *newNode = NULL;

    newNode = (alpha_token_t*) malloc(sizeof(alpha_token_t));

    if(newNode == NULL) {
        printf("No memory...\n");
        exit(1);
    }
    
    if (type == LINE_COMMENT_T) {
       newNode->content = "";
    }
    else if(type == BLOCK_COMMENT_T) {
        newNode->content = "B ... ";
    }
    else if(type == STRING_T) {
        newNode->content = isolate_string();
    }    
    else if(type == BEGINSTATE_FIRST_NODE) {
        /* Nothing */
    }
    else {
        newNode->content = mystrcpy(yytext);
    }
    

    
    newNode->type = type;

    newNode->category = token_category(type);

    newNode->next = NULL;

    if(*lastNode != NULL) {
        newNode->numline = yylineno;
        newNode->numToken = ++token_counter;
        (*lastNode)->next = newNode;
    }
    (*lastNode) = newNode;

    return newNode;
}

char *mystrcpy(char *str) {
    char *buf = malloc(strlen(str));

    if(buf == NULL) {
        printf("No memory... strcpy\n");
        exit(1);
    }
    strcpy(buf, str);
    return buf;
}

char* token_category(TypeToken_t token)
{
    switch(token)
    {
        case IF_T: case ELSE_T: case WHILE_T: case FOR_T: case FUNCTION_T:
        case RETURN_T: case BREAK_T: case CONTINUE_T: case AND_T: case NOT_T:
        case OR_T: case LOCAL_T: case TRUE_T: case FALSE_T: case NIL_T:
            return "KEYWORD";

        case EQUAL_T: case PLUS_T: case MINUS_T: case MUL_T: case DIV_T: case MOD_T:
        case EQUAL_EQUAL_T: case NOT_EQUAL_T: case PLUS_PLUS_T: case MINUS_MINUS_T:
        case GREATER_T: case GREATER_EQUAL_T: case LESS_T: case LESS_EQUAL_T:
            return "OPERATOR";

        case CURLY_O_T: case CURLY_C_T: case SQUARE_BRACKET_O_T: case SQUARE_BRACKET_C_T:
        case DOT_T: case DOT_DOT_T: case PARENTHESIS_O_T: case PARENTHESIS_C_T: case SEMICOLON_T:
        case COMMA_T: case COLON_T: case COLON_COLON_T:
            return "PUNCUATION";

        case LINE_COMMENT_T: case BLOCK_COMMENT_T:
            return "COMMENT";

        case CONST_INT_T:
            return "CONST_INT";

        case CONST_REAL_T:
            return "CONST_REAL";

        case STRING_T:
            return "STRING";

        case ID_T:
            return "ID";

        case BEGINSTATE_FIRST_NODE:
            return "";

        case UNKNOWN_T:
            return "UNKNOWN";

        default: assert(0); /* NEVER */
    }
}

char* token2str(alpha_token_t *token)
{
    switch(token->type)
    {
        case IF_T:               return "IF            <-- enum";
        case ELSE_T:             return "ELSE          <-- enum";
        case WHILE_T:            return "WHILE         <-- enum";
        case FOR_T:              return "FOR           <-- enum";
        case FUNCTION_T:         return "FUNCTION      <-- enum";
        case RETURN_T:           return "RETURN        <-- enum";
        case BREAK_T:            return "BREAK         <-- enum";
        case CONTINUE_T:         return "CONTINUE      <-- enum";
        case AND_T:              return "AND           <-- enum";
        case NOT_T:              return "NOT           <-- enum";
        case OR_T:               return "OR            <-- enum";
        case LOCAL_T:            return "LOCAL         <-- enum";
        case TRUE_T:             return "TRUE          <-- enum";
        case FALSE_T:            return "FALSE         <-- enum";
        case NIL_T:              return "NIL           <-- enum";

        case EQUAL_T:            return "EQUAL         <-- enum";
        case PLUS_T:             return "PLUS          <-- enum";
        case MINUS_T:            return "MINUS         <-- enum";
        case MUL_T:              return "MUL           <-- enum";
        case DIV_T:              return "DIV           <-- enum";
        case MOD_T:              return "MOD           <-- enum";
        case EQUAL_EQUAL_T:      return "EQUAL_EQUAL   <-- enum";
        case NOT_EQUAL_T:        return "NOT_EQUAL     <-- enum";
        case PLUS_PLUS_T:        return "PLUS_PLUS     <-- enum";
        case MINUS_MINUS_T:      return "MINUS_MINUS   <-- enum";
        case GREATER_T:          return "GREATER       <-- enum";
        case GREATER_EQUAL_T:    return "GREATER_EQUAL <-- enum";
        case LESS_T:             return "LESS          <-- enum";
        case LESS_EQUAL_T:       return "LESS_EQUAL    <-- enum";

        case CURLY_O_T:          return "CURLY_O       <-- enum";
        case CURLY_C_T:          return "CURLY_C       <-- enum";
        case SQUARE_BRACKET_O_T: return "SQUARE_BRACKET_O <-- enum";
        case SQUARE_BRACKET_C_T: return "SQUARE_BRACKET_C <-- enum";
        case DOT_T:              return "DOT           <-- enum";
        case DOT_DOT_T:            return "DOT_DOT       <-- enum";
        case PARENTHESIS_O_T:    return "PARENTHESIS_O <-- enum";
        case PARENTHESIS_C_T:    return "PARENTHESIS_C <-- enum";
        case SEMICOLON_T:        return "SEMICOLON     <-- enum";
        case COMMA_T:            return "COMMA         <-- enum";
        case COLON_T:            return "COLON         <-- enum";
        case COLON_COLON_T:      return "COMMA_COLON   <-- enum";

        case LINE_COMMENT_T:     return "LINE_COMMENT  <-- enum";
        case BLOCK_COMMENT_T:    return "BLOCK_COMMENT <-- enum";

        case CONST_INT_T:  case CONST_REAL_T: case STRING_T:
        case ID_T:
           return token->content;

        case BEGINSTATE_FIRST_NODE:
            return "1st Node";
        case UNKNOWN_T:
            return "UNKNOWN";

        default: assert(0); /* NEVER */
    }
}
