## Project phase 5 - hy340
## File: makefile

## ************ Group members: ********************


##      Names        | A.M. |      emails
## -----------------------------------------------

## Kostas Goumas     | 2746 | goumas@csd.uoc.gr



built:
	gcc -g -w vm.c

clean:
	rm a.out
